Mass: 4.2
Inertia: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.15]
NumProps: 6
MaxForce: 20
MinForce: 0.2
MaxError: 0.5
DefaultThrust: 9.5
Moment2Force: 0.025
BladeLength: 0.13
ArmLength: 0.35

UseExp: true
Fex: [0.5, 1.0]
Vex: [0.5, 1.0, 2.0]
Uex: [1, 2]
FV2U_coef: [38.2573, 5.8758, 28.9802, -3.5566, 0.0074]
UV2F_coef: [0.0288, 0.0002, -0.8023, 0.0914, -0.0002]


RPkp: 2
RPki: 0
RPkd: 0

Ykp: 1
Yki: 0
Ykd: 0

Tkp: 3.6 #2
Tki: 0.02 # 0.05 #0.1
Tkd: 3 #6

Posekp: 0.4
Poseki: 0.0008 #0.016
Posekd: 1.0

RposeI: 0
PposeI: 0

windupRP: 5000
windupY: 5000
windupPose: 5000
